name: Helm Chart Build and Deploy

on: 
  push:
    branches:
      - master
      - '*' #Testing purposes

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-central-1
    steps:
      - name: Prepare binaries
        continue-on-error: false
        run: |
          pip install -U awscli
          sudo snap install --classic helm
      - name: Deploy script
        continue-on-error: false
        run: scripts/sync_repo.sh

