name: Helm Chart Build and Deploy

on: 
  push:
    branches:
      - master
      - '*' #Testing purposes

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-central-1
    steps:
      - uses: actions/checkout@v2
      - name: Deploy script
        continue-on-error: false
        run: ./sync_repo.sh

